### ISSUE TITLE
Mobile network

### ISSUE THREAD

**Issue by PatrickSouza8899** [geekydoc/android_device_l70pds#1]
Hello, I enjoyed the ROM optimal performance, only my mobile network CHIP not working says'm not SIM card in the device. Mine is the LG G2 LITE d295f dual chip

**Comment by geekydoc** [comment]
You mean that both modems are not working or only one of them? Would you be able to get a logcat while the device starts?

**Comment by PatrickSouza8899** [comment]
2 is not working, o'que would logcat?

**Comment by geekydoc** [comment]
To learn how to get a logcat, please check out this link: http://android.stackexchange.com/questions/33216/how-can-i-get-a-logcat 

We would like you to do this procedure **just after the CyanogenMod Logo appears and until 20 seconds after you put your pin code for the first sim card.**
