### ISSUE TITLE
Facebook app doesn't work

### ISSUE THREAD

**Issue by lucianojr1** [geekydoc/android_device_l70pds#12]
Facebook app is finding it difficult to work in this ROM, I have already installed the latest versions and the app is crashing and does not work normally. I've tested the same app with the same version in Stock ROM and is normal.

**Comment by geekydoc** [comment]
http://en.miui.com/thread-195550-1-1.html, take a look at this, it might be helpful

**Comment by lucianojr1** [comment]
There is not this libsslx.so file on my system, is there any other way to stabilize the facebook on cm13? 
the facebook app is the most up-to-date version.

**Comment by geekydoc** [comment]
Don't really know anything else. It might be an app bug. Keep it up to date and it might be fixed in the upcoming versions
