### ISSUE TITLE
Wifi and bluetooth

### ISSUE THREAD

**Issue by DouglasD295F** [geekydoc/android_device_l70pds#13]
Wifi and bluetooth 
They are not working 
Lg d295f

**Comment by geekydoc** [comment]
What version are you using? By not working, you mean that the devices will not turn on at all?

**Comment by DouglasD295F** [comment]
Version 1205

**Comment by DouglasD295F** [comment]
I want to connect but not connect.

Turn on and off

**Comment by geekydoc** [comment]
Did it use to work on the previous version?

**Comment by DouglasD295F** [comment]
yes

**Comment by geekydoc** [comment]
I will check this out. I haven't tested the latest build because I am already testing the next release. Please stay with the previous build until this is sorted out.

Thanks

**Comment by DouglasD295F** [comment]
Is there a date for the next version?

**Comment by geekydoc** [comment]
Next release will be the first CyanogenMod 14.1 release. It is expected until tomorrow.

**Comment by DouglasD295F** [comment]
que horas é o lançamento?

**Comment by geekydoc** [comment]
Here it is : http://forum.xda-developers.com/d290n/development/rom-cyanogenmod-14-1-lg-l-fino-t3514200

**Comment by DouglasD295F** [comment]
Friend I installed rom
But bluetooth and wifi are not working
Now neither the sound too
I have a doubt the term flash the rom I did not understand

**Comment by DouglasD295F** [comment]
I speak Portuguese

**Comment by geekydoc** [comment]
Try to make a clean flash. This means that you have to enter the recovery and do a full wipe. See the forum thread on the link above for more information. Then install the zip and reboot the phone. If the problem persists, most probably you are facing a hardware issue. In this case I would recommend to get back to a known working release of the rom, or even the stock rom and see if this issue exists there too.
