### ISSUE TITLE
SIM CARD

### ISSUE THREAD

**Issue by PatrickSouza8899** [geekydoc/android_device_l70pds#6]
The d295f dual chip problem has not yet been fixed, the chip does not work

**Comment by geekydoc** [comment]
Please provide a logcat so I can look into this. There are some users reporting that dual sims are working.

**Comment by PatrickSouza8899** [comment]
How do I provide logcat? I do not know what this is

**Comment by geekydoc** [comment]
Here isva tutorial : http://forum.xda-developers.com/showthread.php?t=1726238

**Comment by geekydoc** [comment]
Also please give me some more information: 
A) Is the second sim card recognised on boot and you just cannot make a phone call, or it does not get recognised at all?
B)Are you using the correct aboot and the correct zip file (l70pds) for your device?

**Comment by PatrickSouza8899** [comment]
I have only one SIM card in my device, yes I am using the correct zip for my device, which in the case is 170pds

**Comment by geekydoc** [comment]
Could you put your sim card in the other slot and try again and report back? If the sim card is not recognised at all, a logcat during boot would be very helpful

**Comment by PatrickSouza8899** [comment]
I've tried and it does not work, in the second slot

**Comment by PatrickSouza8899** [comment]
How do I send you the logcat? I send it to a website and I'll send you the link?

**Comment by geekydoc** [comment]
Yes, try pastebin
